# Generated by Django 5.0.6 on 2024-06-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0005_remove_brand_price_brand_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='shop',
            field=models.IntegerField(),
        ),
    ]