# Generated by Django 5.0.6 on 2024-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0006_alter_brand_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='shop',
            field=models.CharField(max_length=255),
        ),
    ]