# Generated by Django 5.0.6 on 2024-06-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0008_alter_componentpc_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentpc',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]